### PR TITLE
Updated prompt

### PR DESCRIPTION
**Pull request by difagume**
**Previous prompt:**
```
Translate this natural language query into SQL:

"selecciona todos los cars rojos"

Use this table schema:

CREATE TABLE cars (id INT, make TEXT, model TEXT, year INT, color TEXT)

Translate this natural language query into SQL:

"selecciona todos los cars rojos"

SQL Query:
```

**Current prompt:**
```
Translate this natural language query into SQL:

"selecciona todos los cars rojos"

Use this table schema:

CREATE TABLE cars (id INT, make TEXT, model TEXT, year INT, color TEXT)

SQL Query:
```

### CODE REVIEW

**Comment by code-arnab** [comment]
Hey guys, I need a bit of your help. Actually, I started a development server at localhost:3000 but when when I hit translate I am getting this error 👎 

error - pages\api\translate.ts (5:8) @ eval
error - Error: OPENAI_API_KEY is not defined in .env file. Please add it there (see README.md for more details).
    at eval (webpack-internal:///(api)/./pages/api/translate.ts:11:11)
  3 |
  4 | if (!process.env.OPENAI_API_KEY) {
> 5 |   throw new Error(
    |        ^
  6 |     "OPENAI_API_KEY is not defined in .env file. Please add it there (see README.md for more details)."
  7 |   );
  8 | } 

it would be a great help if you know how to fix this

**Comment by difagume** [comment]
> 

you need to create the .env file and inside put your openai Api key, look at the .env.production file, and check the README.md file in section 3 of the Installation.
api
then restart the server to take over the changes in the .ev file

**Comment by whoiskatrin** [comment]
@difagume could you explain a bit more the prompt change? I'm not 1000% convinced that it's the correct one to proceed with.

**Comment by code-arnab** [comment]
@difagume I did what you told but it's still giving me the same error. So, what should I do now

**Pull request merged**
