### PR TITLE
UI IMPROVEMENTS

### PR DESCRIPTION
**Pull request by code-arnab**
1. Added colors to different buttons to better suit the theme
2. Have set a minimum size of the input text area to avoid resizing to very small size

### CODE REVIEW

**Comment by whoiskatrin** [comment]
I’m not sure about the colours change, as we had a design done by one of Vercel designers. @code-arnab

**Comment by code-arnab** [comment]
> I’m not sure about the colours change, as we had a design done by one of Vercel designers. @code-arnab

I understood your point about the design being made by a Vercel designer but my motivation behind this change is that making the UI the a bit more catchy and interactive at the same time because before this change the light mode is just plain white, a blue button and some texts it's the same for the dark mode so I thought changing up the dynamics a bit would make it more fun to interact with.
So, in this update I changed quite a things like added a green color theme to the add schema button and it will change to a red while showing the option remove schema and I also fixed the bug that when you resize the text area it will shrink to such extent that it's just don't look good so I have added a minimum default size to it.
So, I think with these changes the UI would be more fun to interact with at least according to me.

**Comment by whoiskatrin** [comment]
Hey @code-arnab,

Thanks a bunch for putting in the effort to make the UI more interactive and fun. You've got some cool ideas there, and it's clear you've been thinking about how to make the user experience better.

But, you know, we just got this design from a designer and we kinda want to stick with it for a while. We think it's a good idea to let it roll for some time and see how users feel about it before we make any big changes.

Your suggestions are definitely worth keeping in mind, though. So don't toss 'em away! We might want to take another look at them down the road when we're thinking about a design update.

Thanks for understanding, and keep those creative juices flowing!

**Comment by code-arnab** [comment]
Thank you very much for the consideration of my ideas and yeah I think it will be better to let the user's get interact with this a bit more. Meanwhile 
I will keep on looking for new elements or features to add.

**Pull request closed without merging**
