### PR TITLE
correct command for starting dev server

### PR DESCRIPTION
**Pull request by cookabc**
I think starting development server should be: `npm run dev`

If you want to use `npm run start`, you should run `npm run build` first

### CODE REVIEW

**Comment by whoiskatrin** [comment]
Please refer to this page, https://nextjs.org/docs/getting-started

Npm start is a default setup for a project

**Comment by cookabc** [comment]
> 

Hi @whoiskatrin , thanks for the link. But the command **`npm start`** just does not work:
image

Is there anything I missed?

**Comment by shuabrannigan** [comment]
you have to run 'npm run build' to build production 'npm start' then works as intended

maybe an update to the readme to make that clearer?

**Comment by shuabrannigan** [comment]
> I think starting development server should be: `npm run dev`
> 
> If you want to use `npm run start`, you should run `npm run build` first

this is true, readme should reflect this `npm start` only works when application has been built for production

**Pull request merged**
